---
title: "Chip-exo data smoothing(augmentation)"
author: "Dongyue Xie"
date: "June 3, 2018"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
```

The lenght of sequence here is 425, which is not a power of 2 hence causing problem when using smashgen. In this real data analysis, we reflect the data then apply smashgen to the augmented data.

# Setup
```{r}
library(smashrgen)
library(dashr)

extract_counts_CTCF <- function(filename){
  bed_counts <- read.table(filename, header = F, stringsAsFactors = F)
  colnames(bed_counts) <- c("chr", "start", "end", "name", "width", "counts")

  counts <- strsplit(bed_counts$counts, split = ",")[[1]]
  counts[counts == "NA"] <- 0
  counts <- as.numeric(counts)

  return(counts.l = list(chr = bed_counts$chr, start = bed_counts$start, end = bed_counts$end, counts = counts))
}


real_study = function(file.name,plot.name){
  
  chipexo1 <- extract_counts_CTCF(file.name)
  print(paste("proportion of 0s:", round(sum(chipexo1$counts==0)/length(chipexo1$counts),2)))

#dash.out=dash_smooth(chipexo1$counts, dash_control = list(Inf_weight = 1), progressbar = FALSE)
smash.out=smash.poiss(chipexo1$counts)
#y=reflect(chipexo1$counts,'both',c(300,299))
smashgen.vst.out=smash.gen.poiss(chipexo1$counts,method = 'smash',transformation = 'vst')
smashgen.lik.out=smash.gen.poiss(chipexo1$counts,method = 'smash',
                                 transformation = 'lik_expansion',ash.pm = TRUE)

plot(chipexo1$counts, col = "gray80", type = "h", ylab = "counts", xlab = "", main = plot.name)
lines(smash.out, col = "blue", lwd = 1)
#lines(dash.out$estimate, col = "red", lwd = 1)
lines(smashgen.vst.out$lambda.est,col="red",lwd=2)
lines(smashgen.lik.out$lambda.est,col='black',lwd=2)

legend("topright", # places a legend at the appropriate place
       c("data","smash-poiss",'smash-gen-vst','smash-gen-lik'), # puts text in the legend
       lty=c(1,1,1,1), # gives the legend appropriate symbols (lines)
       lwd=c(1,1,2,2),
       cex = 0.5,
       col=c("gray80","blue", "red",'black'))

print(paste("nugget effect estimated by vst:",round(smashgen.vst.out$nugget.est,2)))
print(paste("nugget effect estimated by lik_expansion:",round(smashgen.lik.out$nugget.est,2)))

}

```

# EncodeBroadHistoneHelas - Rep 1

## Forward

```{r}
file.name = "data/chipexo_examples/example_CTCF_MACE_wgEncodeBroadHistoneHelas3CtcfStdAlnRep1_forward_counts.txt"
real_study(file.name,plot.name = "EncodeBroadHistoneHelas - Rep 1 - forward")
```

## Reverse

```{r}
file.name = "data/chipexo_examples/example_CTCF_MACE_wgEncodeBroadHistoneHelas3CtcfStdAlnRep1_reverse_counts.txt"

real_study(file.name,plot.name = "EncodeBroadHistoneHelas - Rep 1 - reverse")
```

# EncodeOpenChromChipHelas - Rep 1

## Forward

```{r}
file.name = "data/chipexo_examples/example_CTCF_MACE_wgEncodeOpenChromChipHelas3CtcfAlnRep1_forward_counts.txt"


real_study(file.name,plot.name = "EncodeOpenChromChipHelas - Rep 1 - Forward")
```

## Reverse

```{r}
file.name = "data/chipexo_examples/example_CTCF_MACE_wgEncodeOpenChromChipHelas3CtcfAlnRep1_reverse_counts.txt"

real_study(file.name,plot.name = "EncodeOpenChromChipHelas - Rep 1 - reverse")
```

# EncodeOpenChromChipHelas - Rep 2

##Forward

```{r}
file.name = 'data/chipexo_examples/example_CTCF_MACE_wgEncodeOpenChromChipHelas3CtcfAlnRep2_forward_counts.txt'
real_study(file.name,plot.name = "EncodeOpenChromChipHelas - Rep 2 - Forward")
```

# Reverse

```{r}
file.name = "data/chipexo_examples/example_CTCF_MACE_wgEncodeOpenChromChipHelas3CtcfAlnRep2_reverse_counts.txt"
real_study(file.name,plot.name = "EncodeOpenChromChipHelas - Rep 2 - reverse")
```
