---
title: "One iteration"
author: "Dongyue Xie"
date: "May 8, 2018"
output: html_document
---

```{r}
#' smash generaliation function

#' A modified version. Instead of input \sigma^2+s_t^2 and estiamte \mu_t, we simply input s_t^2 and after convergence, input both to estimate the final \mu_t.

#' This function is for $Y_t=\mu_t+N(0,s_t^2)+N(0,\sigma^2)$ with known $s_t^2$ and $\sigma^2$.


#' @param x: a vector of observations
#' @param sigma: standard deviations, scalar.
#' @param family: choice of wavelet basis to be used, as in wavethresh.
#' @param niter: number of iterations for IRLS
#' @param tol: tolerance of the criterion to stop the iterations


smash.gen=function(x,sigma,family='DaubExPhase',niter=30,tol=1e-2){
  mu=c()
  s=c()
  y=c()
  munorm=c()
  mu=rbind(mu,rep(mean(x),length(x)))
  s=rbind(s,rep(1/mu[1],length(x)))
  y=rbind(y,log(mean(x))+(x-mean(x))/mean(x))
  for(i in 1:niter){
    vars=ifelse(s[i,]<0,1e-8,s[i,])
    mu.hat=smash.gaus(y[i,],sigma=sqrt(vars))#mu.hat is \mu_t+E(u_t|y)
    
    mu=rbind(mu,mu.hat)
    munorm[i]=norm(mu.hat-mu[i,],'2')
    if(munorm[i]<tol){
      break
    }
    #update m and s_t
    mt=exp(mu.hat)
    s=rbind(s,1/mt)
    y=rbind(y,log(mt)+(x-mt)/mt)
    
    
  }
  mu.hat=smash.gaus(y[i,],sigma = sqrt(sigma^2+ifelse(s[i,]<0,1e-8,s[i,])))
  return(list(mu.hat=mu.hat,mu=mu,s=s,y=y,munorm=munorm))
}

```

```{r}
#' Simulation study comparing smash and smashgen

simu_study=function(m,sigma,seed=1234,
                    niter=1,family='DaubExPhase',tol=1e-2,
                    reflect=FALSE){
  set.seed(seed)
  lamda=exp(m+rnorm(length(m),0,sigma))
  x=rpois(length(m),lamda)
  #fit data
  smash.out=smash.poiss(x,reflect=reflect)
  smash.gen.out=smash.gen(x,sigma=sigma,niter=niter,family = family,tol=tol)
  return(list(smash.out=smash.out,smash.gen.out=exp(smash.gen.out$mu.hat),smash.gen.est=smash.gen.out,x=x,loglik=smash.gen.out$loglik))
}

```

# Simulation 1: Constant trend Poisson nugget

## $\sigma=0.01$

```{r}
library(smashr)
m=rep(3,256)
simu.out=simu_study(m,0.01)

#par(mfrow = c(1,2))

plot(simu.out$x,col = "gray80" ,ylab = '')
lines(simu.out$smash.gen.out, col = "red", lwd = 2)
lines(exp(m))
legend("topright", # places a legend at the appropriate place
       c("truth","smash-gen"), # puts text in the legend
       lty=c(1,1), # gives the legend appropriate symbols (lines)
       lwd=c(1,1),
       cex = 1,
       col=c("black","red", "blue"))

plot(simu.out$x,col = "gray80" ,ylab = '')
lines(simu.out$smash.out, col = "blue", lwd = 2)
lines(exp(m))
legend("topright", 
       c("truth", "smash"), 
       lty=c(1,1), 
       lwd=c(1,1),
       cex = 1,
       col=c("black", "blue"))
```

## $\sigma=0.1$

```{r}

simu.out=simu_study(m,0.1)

#par(mfrow = c(1,2))

plot(simu.out$x,col = "gray80" ,ylab = '')
lines(simu.out$smash.gen.out, col = "red", lwd = 2)
lines(exp(m))
legend("topright", 
       c("truth","smash-gen"), 
       lty=c(1,1), 
       lwd=c(1,1),
       cex = 1,
       col=c("black","red", "blue"))

plot(simu.out$x,col = "gray80" ,ylab = '')
lines(simu.out$smash.out, col = "blue", lwd = 2)
lines(exp(m))
legend("topright", 
       c("truth", "smash"), 
       lty=c(1,1), 
       lwd=c(1,1),
       cex = 1,
       col=c("black", "blue"))
```


## $\sigma=0.5$

```{r}

simu.out=simu_study(m,0.5)

#par(mfrow = c(1,2))

plot(simu.out$x,col = "gray80" ,ylab = '')
lines(simu.out$smash.gen.out, col = "red", lwd = 2)
lines(exp(m),col='gray80')
legend("topright", 
       c("truth","smash-gen"), 
       lty=c(1,1), 
       lwd=c(1,1),
       cex = 1,
       col=c("black","red", "blue"))

plot(simu.out$x,col = "gray80" ,ylab = '')
lines(simu.out$smash.out, col = "blue", lwd = 2)
lines(exp(m),col='gray80')
legend("topright", 
       c("truth", "smash"), 
       lty=c(1,1), 
       lwd=c(1,1),
       cex = 1,
       col=c("black", "blue"))
```

## $\sigma=1$

```{r}

simu.out=simu_study(m,1)

#par(mfrow = c(1,2))

plot(simu.out$x,col = "gray80" ,ylab = '')
lines(simu.out$smash.gen.out, col = "red", lwd = 2)
lines(exp(m),col='black')
legend("topleft", 
       c("truth","smash-gen"), 
       lty=c(1,1), 
       lwd=c(1,1),
       cex = 1,
       col=c("black","red", "blue"))

plot(simu.out$x,col = "gray80" ,ylab = '')
lines(simu.out$smash.out, col = "blue", lwd = 2)
lines(exp(m),col='black')
legend("topleft", 
       c("truth", "smash"), 
       lty=c(1,1), 
       lwd=c(1,1),
       cex = 1,
       col=c("black", "blue"))
```

# Simulation 2: Step trend 

## $\sigma=0.01$

```{r}
m=c(rep(3,128), rep(5, 128), rep(6, 128), rep(3, 128))
simu.out=simu_study(m,0.01)

#par(mfrow = c(1,2))

plot(simu.out$x,col = "gray80" ,ylab = '')
lines(simu.out$smash.gen.out, col = "red", lwd = 2)
lines(exp(m))
legend("topright", 
       c("truth","smash-gen"), 
       lty=c(1,1), 
       lwd=c(1,1),
       cex = 1,
       col=c("black","red", "blue"))

plot(simu.out$x,col = "gray80" ,ylab = '')
lines(simu.out$smash.out, col = "blue", lwd = 2)
lines(exp(m))
legend("topright", 
       c("truth", "smash"), 
       lty=c(1,1), 
       lwd=c(1,1),
       cex = 1,
       col=c("black", "blue"))
```

## $\sigma=0.1$

```{r}

simu.out=simu_study(m,0.1)

#par(mfrow = c(1,2))

plot(simu.out$x,col = "gray80" ,ylab = '')
lines(simu.out$smash.gen.out, col = "red", lwd = 2)
lines(exp(m))
legend("topright", 
       c("truth","smash-gen"), 
       lty=c(1,1), 
       lwd=c(1,1),
       cex = 1,
       col=c("black","red", "blue"))

plot(simu.out$x,col = "gray80" ,ylab = '')
lines(simu.out$smash.out, col = "blue", lwd = 2)
lines(exp(m))
legend("topright", 
       c("truth", "smash"), 
       lty=c(1,1), 
       lwd=c(1,1),
       cex = 1,
       col=c("black", "blue"))
```

## $\sigma=0.5$

```{r}

simu.out=simu_study(m,0.5)

#par(mfrow = c(1,2))

plot(simu.out$x,col = "gray80" ,ylab = '')
lines(simu.out$smash.gen.out, col = "red", lwd = 2)
lines(exp(m))
legend("topright", 
       c("truth","smash-gen"), 
       lty=c(1,1), 
       lwd=c(1,1),
       cex = 1,
       col=c("black","red", "blue"))

plot(simu.out$x,col = "gray80" ,ylab = '')
lines(simu.out$smash.out, col = "blue", lwd = 2)
lines(exp(m))
legend("topright", 
       c("truth", "smash"), 
       lty=c(1,1), 
       lwd=c(1,1),
       cex = 1,
       col=c("black", "blue"))
```

## $\sigma=1$

```{r}

simu.out=simu_study(m,1)

#par(mfrow = c(1,2))

plot(simu.out$x,col = "gray80" ,ylab = '')
lines(simu.out$smash.gen.out, col = "red", lwd = 2)
lines(exp(m))
legend("topleft", 
       c("truth","smash-gen"), 
       lty=c(1,1), 
       lwd=c(1,1),
       cex = 1,
       col=c("black","red", "blue"))

plot(simu.out$x,col = "gray80" ,ylab = '')
lines(simu.out$smash.out, col = "blue", lwd = 2)
lines(exp(m))
legend("topleft", 
       c("truth", "smash"), 
       lty=c(1,1), 
       lwd=c(1,1),
       cex = 1,
       col=c("black", "blue"))
```
