---
title: "Poisson data with unknown nugget effect"
author: "Dongyue Xie"
date: "2019-11-18"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction


Now we are ready to apply smashgen to Poisson data with unknown nugget effect. It's very important to note that when the range of mean function is small, the $SNR=\frac{sd(mu)}{mean[sd(noise)]}$ could be very large. For example, if the mean function is spike and has range [1,3]. Then the stand deviation of mean function is around 0.48 and the average of $s_t^2=1/e^\mu_t$ is around 0.92. So even without nugget effect, the SNR is already about 0.52. Adding the nugget effect would make it smaller. SNR in this situation matters to smashgen because we are using Gaussian approximation to it so a very low SNR would make it very difficult to recover the true mean. This is the reason why smashgen performs poorly when the range of mean function is small.

From 3, when the scale of mean function is small(smallest around 0.1-0.3),  smash outperforms smashgen under all the mean functions. From 4, when we increased the scale of mean function(smallest around 50, largest around 200), smashgen outperforms smash for almost all the functions except Doppler. Smashgen cannot capture the high frequency fluctuation of Doppler at the beginning. For Heavysine, Parabola, Wave and timeshifted mean functions, using symmlet8 basis outperforms using Haar basis.

In 5, we compared smash and smashgen on estimating on estimating $\mu$ and $\log\mu$. For step function, smashgen gives better estimate of $\log\mu$ but worse estimation of $\mu$. For heavysine, smash and smashgen are similar while smashgen with symmlet8 achieved lower MSE when mean function range is (50,100). For Doppler, smashgen with symmlet8 achieved lower MSE when mean function range is (50,100). For parabola, the two methods are similar. For wave, smashgen with symmlet8 won. It's very interesting to see that though smashgen gave smaller MSE for estimating $\log\mu$, the MSE for estimating $\mu$ became larger, for example in step and bump functions. 

2. [Haar vs Symmlet 8](wavebasis.html): a comparison of different wavelet basis.
3. [Poisson data, wavelet basis functions](poiwave.html): no nugget effect.
4. [Poisson data, wavelet basis functions:larger mean function](poiwave2.html)
5. [Poisson seq, compare smash and smashgen on the estimate of $\mu$ and $\log\mu$](poiwavelog.html)

```{r}

```

