---
title: "Compare VST and lik-expansion methods"
author: "Dongyue Xie"
date: "June 3, 2018"
output: html_document
---

```{r}
library(smashrgen)
library(smashr)
library(wavethresh)

```



## step trend

### Generate from log-link model

```{r}
set.seed(12345)
sigma = 0
n = 1024
m=c(rep(1,n/4), rep(5, n/4), rep(10, n/4), rep(1, n/4))
lamda=exp(log(m)+rnorm(length(m),0,sigma))
x=rpois(length(m),lamda)
fit = smash.gen.poiss(x,transformation = 'lik_expansion',method = 'smash',ash.pm = TRUE)
fit2 = smash.gen.poiss(x,transformation = 'vst',method = 'smash')
plot(x,col='grey80')
lines(m+sigma^2/2,col='grey50')
lines(fit$lambda.est,col=1,lwd=2)
lines(fit2$lambda.est,col=2,lwd=2)
lines(smash.poiss(x),col=4)
legend('topright',c("true mean","lik_expansion","vst","smash"),lty=c(1,1,1,1),lwd=c(1,2,2,1),col=c('grey50',1,2,4))
fit$nugget.est
fit2$nugget.est
```



```{r}
set.seed(12345)
sigma = 0.5
n = 1024
m=c(rep(1,n/4), rep(5, n/4), rep(8, n/4), rep(1, n/4))
lamda=exp(log(m)+rnorm(length(m),0,sigma))
x=rpois(length(m),lamda)
fit = smash.gen.poiss(x,transformation = 'lik_expansion',method = 'smash',ash.pm = TRUE)
fit2 = smash.gen.poiss(x,transformation = 'vst',method = 'smash')
plot(x,col='grey80')
lines(m+sigma^2/2,col='grey50')
lines(fit$lambda.est,col=1,lwd=2)
lines(fit2$lambda.est,col=2,lwd=2)
#lines(smash.poiss(x),col=4)
legend('topright',c("true mean","lik_expansion","vst"),lty=c(1,1,1),lwd=c(1,2,2),col=c('grey50',1,2))
fit$nugget.est
fit2$nugget.est
```

```{r}
set.seed(12345)
sigma = 0.5
n = 1024
m=c(rep(1,n/4), rep(5, n/4), rep(8, n/4), rep(1, n/4))*5
lamda=exp(log(m)+rnorm(length(m),0,sigma))
x=rpois(length(m),lamda)
fit = smash.gen.poiss(x,transformation = 'lik_expansion',method = 'smash',ash.pm = TRUE)
fit2 = smash.gen.poiss(x,transformation = 'vst',method = 'smash')
plot(x,col='grey80')
lines(m+sigma^2/2,col='grey50')
lines(fit$lambda.est,col=1,lwd=2)
lines(fit2$lambda.est,col=2,lwd=2)
#lines(smash.poiss(x),col=4)
legend('topright',c("true mean","lik_expansion","vst"),lty=c(1,1,1),lwd=c(1,2,2),col=c('grey50',1,2))
fit$nugget.est
fit2$nugget.est
```


### Generate from sqrt-root link

```{r}
set.seed(12345)
sigma = 0.5
n = 1024
m=c(rep(1,n/4), rep(5, n/4), rep(8, n/4), rep(1, n/4))
lamda=(sqrt(m)+rnorm(length(m),0,sigma))^2
x=rpois(length(m),lamda)
fit = smash.gen.poiss(x,transformation = 'lik_expansion',method = 'smash',ash.pm = TRUE,nug.init = NULL)
fit2 = smash.gen.poiss(x,transformation = 'vst',method = 'smash',ash.pm = TRUE)
plot(x,col='grey80')
lines(m+sigma^2,col='grey50')
lines(fit$lambda.est,col=1,lwd=2)
lines(fit2$lambda.est,col=2,lwd=2)
#lines(smash.poiss(x),col=4)
legend('topright',c("true mean","lik_expansion","vst"),lty=c(1,1,1),lwd=c(1,2,2),col=c('grey50',1,2))
fit$nugget.est
fit2$nugget.est
```


```{r}
set.seed(12345)
sigma = 1.5
n = 1024
m=c(rep(1,n/4), rep(5, n/4), rep(8, n/4), rep(1, n/4))*5
lamda=(sqrt(m)+rnorm(length(m),0,sigma))^2
x=rpois(length(m),lamda)
fit = smash.gen.poiss(x,transformation = 'lik_expansion',method = 'smash',ash.pm = TRUE,nug.init = NULL)
fit2 = smash.gen.poiss(x,transformation = 'vst',method = 'smash',nug.init = NULL)
plot(x,col='grey80')
lines(m+sigma^2,col='grey50')
lines(fit$lambda.est,col=1,lwd=2)
lines(fit2$lambda.est,col=2,lwd=2)
#lines(smash.poiss(x),col=4)
legend('topright',c("true mean","lik_expansion","vst"),lty=c(1,1,1),lwd=c(1,2,2),col=c('grey50',1,2))
fit$nugget.est
fit2$nugget.est
```
